#### Iris flower specie detection

In [ ]:
# required libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 


In [17]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()

# prints the dataset-related detail comprehensively
# print(iris_dataset)
# print(iris_dataset.keys())
# print(iris_dataset.feature_names)
# print(iris_dataset.target)
# print(iris_dataset['DESCR'])
print("First 5 columns of data:\n {}".format(iris_dataset["data"][:5]))
print("target classes are denoted as: \n {}".format(iris_dataset["target"][::51]))

First 5 columns of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
target classes are denoted as: 
 [0 1 2]


In [16]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0
)
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)
